### ISSUE TITLE
Improve scraping of labs with specific meeting dates/times

### ISSUE THREAD

**Issue by glitch452** [andrewnags/uOcourses#11]
I'm wondering if we can improve the scraping/parsing of the labs with specific (and multiple) meeting dates/times. 

Ie. CHM 1321 ...
![image](https://user-images.githubusercontent.com/894128/77028727-0f2bbe00-6970-11ea-8c4e-d168017136fd.png)

Currently, the scraper seems to be gathering the last time slot in the list, which is not the same as the rest.  In terms of creating a weekly schedule, it might be a good idea to compare the various options and give the overall result of the largest time slot, since it would encompass the smaller one also in the weekly schedule.  

Of course, if the time slots just don't overlap at all, this is another issue to handle.  Maybe we need to be able to handle multiple time slots for a component?

Also, it would be nice to capture somewhere the dates and times for each session.  Not necessary for making a weekly schedule, but for generating a calendar feed, it would be very useful to only include the components on days that they are actually scheduled.  Or at the very least, include the scheduled dates in the calendar item description.

**Comment by andrewnags** [comment]
This issue seems to be occuring downstream of the scraper, so I'm going to close this issue.
